name: app-server-deploy

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::722015880532:role/GitHubActionsRoll'

      - name: ssm send-command
        run: |
          export RESPONSE=$(aws ssm send-command \
            --instance-ids ${{ secrets.TARGET_1 }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo su - ec2-user -c \"cd /var/www/testRepo && git pull\""
            ]' \
            )

      - name: deployed message
        run: echo 'INSTANCE_ID=${{ secrets.TARGET_1 }}へデプロイが完了'
