name: cfn-linter

on:
  - push
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install cfn-lint
        shell: bash
        run: pip3 install cfn-lint
      
      - name: cfn-lint
        shell: bash
        run: |
          cfn-lint template/test.yml